version: '3'

services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: ${MARIADB_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nextcloud:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    depends_on:
      - mariadb
    links:
    - mariadb:mariadb
    image: ${NEXTCLOUD_IMAGE}:${NEXTCLOUD_TAG}
    hostname: ${DOMAIN}
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - config:/var/www/html/config
      - apps:/var/www/html/apps
      - custom_apps:/var/www/html/custom_apps
      - data:/var/www/html/data
      - themes:/var/www/html/themes/custom_theme
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}
      NEXTCLOUD_TRUSTED_DOMAINS: ${DOMAIN}
      NEXTCLOUD_UPDATE: 1
      MYSQL_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT}
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}

volumes:
  mariadb:
  nextcloud:
  config:
  apps:
  custom_apps:
  data:
  themes:

networks:
  default:
    name: ${NETWORK}
    external: true

