services:
  gitlab-ce:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    hostname: ${GITLAB_HOSTNAME}
    image: ${GITLAB_CE_IMAGE}:${GITLAB_CE_TAG}
    restart: always
    environment:
      TZ: ${TZ}
      # VIRTUAL_HOST: ${GITLAB_HOST},${GITLAB_REGISTRY},${GITLAB_PAGES}
      # LETSENCRYPT_HOST: ${GITLAB_HOST},${GITLAB_REGISTRY},${GITLAB_PAGES}
      #SSH_HOST: ${GITLAB_HOST}
      #SSH_PORT: ${GITLAB_CE_SSH_PORT}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOST}'
        letsencrypt['enable'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_CE_SSH_PORT}
    ports:
      - "${GITLAB_CE_SSH_PORT}:22"
      #- "${GITLAB_CE_REGISTRY_PORT}:5000"
    volumes:
      - /srv/gitlab/data:/var/opt/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/config:/etc/gitlab
    shm_size: '256m'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${GITLAB_HOST}`)"
      - "traefik.http.routers.gitlab.service=${COMPOSE_PROJECT_NAME}-app"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"

networks:
  default:
    name: ${NETWORK}
    external: true
